version: '3.8'
services:
  binance-news:
    build: .
    container_name: binance-news
    volumes:
      - type: bind
        source: .
        target: /app
    environment:
      - TZ=Asia/Shanghai
      - IS_DOCKER=true
      - HTTP_PROXY=http://host.docker.internal:7890
      - HTTPS_PROXY=http://host.docker.internal:7890
      - PLAYWRIGHT_BROWSERS_PATH=/ms-playwright
    cap_add:
      - SYS_ADMIN
    shm_size: '0.5gb'
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always